# Copyright 2020-2021 Ian Jackson and contributors to Otter
# SPDX-License-Identifier: AGPL-3.0-or-later
# There is NO WARRANTY.

table_size = [180, 60]

[[pieces]]
pos = [90,40]
type = "Disc"
diam = 10
faces = ["red","grey"]
edges = ["black","white"]

[[pieces]]
pos = [90, 20]
type = "Rect"
size = [10]
angle.Compass = 1
faces = ["blue", "grey"]

[[pieces]]
pos = [150,40]
type = "Lib"
lib = "wikimedia"
item = "chess-w-B"

[[pieces]]
pos = [160,40]
type = "Lib"
angle.Compass = 1
lib = "wikimedia"
item = "chess-b-N"

[[pieces]]
pos = [120, 30]
type = "Rect"
size = [10]
angle.Compass = 1
faces = [ ]
edges = ["yellow", "orange"]
edge_width = 0.5

[[pieces]]
pos = [40, 40]
type = "Hand"
edge = "white"
colour = "grey"
label.place = "TopLeftOutside"
	shape.type = "Rect"
shape.xy = [70,20]

[[pieces]]
pos = [150,30]
type = "Lib"
lib = "wikimedia"
item = "chess-w-P"

[[pieces]]
pos = [160,30]
type = "Lib"
lib = "wikimedia"
item = "chess-b-P"

[[pieces]]
pos = [155, 15]
type = "Die"
labels = ["A", "B"]
image.type = "Disc"
image.diam = 12
circle_scale = 0.833
image.edges = ["black","black"]
image.faces = ["#ccccff", "#ccffcc"]

[[pieces]]
pos = [140, 15]
type = "Die"
labels = 6
desc = "a pink die"
occult.ilk = "d6-pink"
occult.label = "?"
image.type = "Rect"
image.size = [10]
image.edges = ["black"]
image.faces = ["#ff8888"]

[[pieces]]
pos = [125, 15]
type = "Die"
desc = "a red die"
labels = 6
occult.ilk = "d6-red"
occult.label = "?"
image.type = "Rect"
image.size = [10]
image.edges = ["white"]
image.faces = ["#ff0000"]

[[pieces]]
pos = [125, 45]
type = "Currency"
qty = 400
min_unit = 5
currency = "Æ’"
image.type = "Rect"
image.size = [20,7]
image.edges = ["#00ff00"]
image.faces = ["#008800"]
